CONFIG_LOG=y
CONFIG_ASSERT=y
CONFIG_NET_BUF=y
CONFIG_ZCBOR=y
CONFIG_MCUMGR=y
CONFIG_IMG_MANAGER=y
CONFIG_MCUMGR_GRP_IMG=y
CONFIG_MCUMGR_GRP_OS=y
CONFIG_MCUMGR_TRANSPORT_NETBUF_SIZE=517
CONFIG_BT=y
CONFIG_BT_CUSTOM=y
CONFIG_MCUBOOT_BLE=y

CONFIG_STREAM_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH=y

CONFIG_FRAME=y
CONFIG_REGULATOR=n

# File system
CONFIG_SETTINGS=y
CONFIG_SETTINGS_RUNTIME=y
CONFIG_SETTINGS_FILE=y

CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
# must start with /lfs/
CONFIG_SETTINGS_FILE_PATH="/lfs/settings"

CONFIG_BOOT_MAX_IMG_SECTORS=1024

CONFIG_BOOT_BLE_DFU_ENTRANCE_GPIO=y
CONFIG_BOOT_BLE_DFU_DETECT_DELAY=10
CONFIG_BOOT_BLE_DFU_IDLE_TIMEOUT=120
CONFIG_MCUBOOT_INDICATION_LED=y
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_PWM=y
CONFIG_LED_PWM=y
CONFIG_LED_INIT_PRIORITY=50
CONFIG_ALIF_VBAT=y
CONFIG_QMC6308=n
CONFIG_BMA530=n
CONFIG_REGULATOR=y

# CONFIG_LOG=y
# CONFIG_ASSERT=y
# CONFIG_FRAME_LOG_LEVEL_DBG=y